In [1]:
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### Use python's built in functionality/operators to determine the following:

#### 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

#### 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

#### 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

####  4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

####  5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

####  6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

####  7 - Make a variable named odds_in_a. It should hold only the odd numbers

####  8 - Make a variable named evens_in_a. It should hold only the evens.


In [12]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

sum_of_a = sum(a)
sum_of_a

55

In [4]:
min_of_a = np.min(a)
min_of_a

1

In [5]:
max_of_a = np.max(a)
max_of_a

10

In [7]:
mean_of_a = sum(a)/len(a)
mean_of_a

5.5

In [8]:
product_of_a = np.product(a)
product_of_a

3628800

In [13]:
squares_of_a = a ** 2
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [14]:
odds_in_a = a[a % 2 == 1]
odds_in_a

array([1, 3, 5, 7, 9])

In [15]:
evens_in_a = a[a % 2 == 0]

evens_in_a

array([ 2,  4,  6,  8, 10])

<hr style="border:2px solid black">

## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: 
Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
<br>

b = [
    [3, 4, 5],
    [6, 7, 8]
]

#### 9 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

#### 10- refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

#### 11- refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])


#### 12 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

#### 13 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

#### 14 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)


#### 15 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)


#### 16 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

#### 17 - print out the shape of the array b.

#### 18 - transpose the array b.

#### 19 - reshape the array b to be a single list of 6 numbers. (1 x 6)

#### 1 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)





In [16]:
b = [ [3, 4, 5], [6, 7, 8] ]
b = np.array(b)

In [18]:
sum_of_b = b.sum()
sum_of_b

33

In [19]:
np.min(b)

3

In [20]:
indices=np.where(b==b.max())
print(b[indices])

[8]


In [21]:
b.mean()

5.5

In [22]:
np.prod(b)

20160

In [23]:
squares_of_b = b **2
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [24]:
b[b % 2 != 0]

array([3, 5, 7])

In [25]:
b[b % 2 == 0]

array([4, 6, 8])

In [26]:
print(b)
print(b.shape)

[[3 4 5]
 [6 7 8]]
(2, 3)


In [27]:
transpose_b = np.transpose(b)

transpose_b

array([[3, 6],
       [4, 7],
       [5, 8]])

In [28]:
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

In [29]:
np.reshape(b, (6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

<hr style="border:2px solid black">

## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

<br>
HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.



#### 2 - Find the min, max, sum, and product of c.

#### 3 - Determine the standard deviation of c.

#### 4 - Determine the variance of c.

#### 5- Print out the shape of the array c

#### 6 - Transpose c and print out transposed result.

#### 7 - Get the dot product of the array c with c. 

#### 8 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

#### 9 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.


In [30]:
c = [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]
c = np.array(c)

print(np.min(c))
print(np.max(c))
print(np.sum(c))
print(np.product(c))

1
9
45
362880


In [31]:
c_std = np.std(c)

c_std

2.581988897471611

In [32]:
c.var()

6.666666666666667

In [33]:
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [36]:
transpose_c = np.transpose(c)

In [35]:
dot_product_of_c = np.dot(c, c)
dot_product_of_c

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [39]:
cat = transpose_c * c
np.sum(cat)

261

In [43]:
np.product(cat)

131681894400

<hr style="border:2px solid black">

## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

#### 10 - Find the sine of all the numbers in d

#### 11 - Find the cosine of all the numbers in d

#### 12 - Find the tangent of all the numbers in d

#### 13 - Find all the negative numbers in d

#### 14 - Find all the positive numbers in d

#### 15 - Return an array of only the unique numbers in d.

#### 16 - Determine how many unique numbers there are in d.

#### 17 - Print out the shape of d.

#### 18 - Transpose and then print out the shape of d.

#### 19 - Reshape d into an array of 9 x 2

In [44]:
d = [ [90, 30, 45, 0, 120, 180], [45, -90, -30, 270, 90, 0], [60, 45, -45, 90, -45, 180] ]

d = np.array(d)

In [45]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [46]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [48]:
tan_values = np.tan(d)
tan_values

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [49]:
negd = (d < 0)
negd

array([[False, False, False, False, False, False],
       [False,  True,  True, False, False, False],
       [False, False,  True, False,  True, False]])

In [50]:
d[d>0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [51]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [54]:
np.count_nonzero(np.unique(d)) + np.count_nonzero(np.unique(d == 0))
len(np.unique(d))

11

In [56]:
print(d)
print(d.shape)

[[ 90  30  45   0 120 180]
 [ 45 -90 -30 270  90   0]
 [ 60  45 -45  90 -45 180]]
(3, 6)


In [57]:
d.transpose().shape

(6, 3)