# Numpy Exercises Question 8

In [1]:
import numpy as np

<hr style="border:1px solid gray">

## Setup #1

In [2]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### #1. Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [3]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [4]:
sum_of_a = a.sum()
sum_of_a

55

#### #2. - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [5]:
min_of_a = a.min()
min_of_a

1

#### #3. Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [6]:
max_of_a = a.max()
max_of_a

10

#### #4. Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [7]:
mean_of_a = a.mean()
mean_of_a

5.5

In [8]:
#Teacher example:
mean_of_a = sum(a)/len(a)
mean_of_a

5.5

#### #5. Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [9]:
product_of_a = np.prod(a)
product_of_a

3628800

In [10]:
#Teacher example:
product_of_a = 1
for n in a:
    product_of_a *= n
    
product_of_a

3628800

#### #6.  Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [11]:
square_of_a = np.square(a)
square_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [12]:
#Teacher example:
squares_of_a = [n**2 for n in a]
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

#### #7. Make a variable named odds_in_a. It should hold only the odd numbers

In [13]:
odds_in_a = a[a % 2 !=0]
odds_in_a

array([1, 3, 5, 7, 9])

In [14]:
#Teacher example:
odds_in_a = [n for n in a if n % 2 == 1]
odds_in_a

[1, 3, 5, 7, 9]

#### #8. Make a variable named evens_in_a. It should hold only the evens

In [15]:
evens_in_a = a[a % 2 ==0]
evens_in_a

array([ 2,  4,  6,  8, 10])

In [16]:
#Teacher example:
odds_in_a = [n for n in a if n % 2 == 0]
odds_in_a

[2, 4, 6, 8, 10]

<hr style="border:2px solid black">

## Setup #2

What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

- Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists. b = [ [3, 4, 5], [6, 7, 8] ]


In [17]:
b = np.array ([
    [3, 4, 5],
    [6, 7, 8]
])

#### #1. refactor the following to use numpy. Use sum_of_b as the variable. Hint, you'll first need to make sure that the "b" variable is a numpy array


In [19]:
sum_of_b = b.sum()
sum_of_b

33

#### #2. refactor the following to use numpy. 

In [20]:
min_of_b = b.min()
min_of_b

3

#### #3. refactor the following maximum calculation to find the answer with numpy.

In [21]:
max_of_b = b.max()
max_of_b

8

#### #4. refactor the following using numpy to find the mean of b

In [22]:
mean_of_b = b.mean()
mean_of_b

5.5

#### #5. refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [23]:
prod_of_b = np.prod(b)
prod_of_b

20160

In [24]:
#Teacher example:
product_of_b = b.prod()
product_of_b

20160

#### #6. refactor the following to use numpy to find the list of squares 

In [25]:
square_of_b = np.square(b)
square_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [27]:
#Teacher example:
squares_of_b = b ** 2

#### #7. refactor using numpy to determine the odds_in_b

In [28]:
odds_in_b = b[b % 2 !=0]
odds_in_b

array([3, 5, 7])

#### #8. refactor the following to use numpy to filter only the even numbers

In [30]:
evens_in_b = b[b % 2 ==0]
evens_in_b

array([4, 6, 8])

#### #9. print out the shape of the array b.

In [32]:
print(b.shape)

(2, 3)


#### #10. transpose the array b.

In [33]:
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [34]:
#Teacher example:
b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

#### #11. reshape the array b to be a single list of 6 numbers. (1 x 6)

In [35]:
np.reshape(b, (1,6))

array([[3, 4, 5, 6, 7, 8]])

#### #12. reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [36]:
np.reshape(b, (6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [37]:
#You can not know how many rows or columns you need
#you can use -1 if you only know one (rows or columns)
#Teacher example:

b.reshape(6,-1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

<hr style="border:2px solid black">

## Setup #3

In [38]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [39]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [40]:
#Teacher Example:
#can also say:
c = np.array(c)

#### #1. Find the min, max, sum, and product of c.

In [41]:
c.min()

1

In [42]:
c.max()

9

In [43]:
c.sum()

45

In [44]:
np.prod(c)

362880

In [45]:
c.min(), c.max(), c.sum(), np.prod(c)

(1, 9, 45, 362880)

#### #2. Determine the standard deviation of c.

In [46]:
np.std(c)

2.581988897471611

#### #3. Determine the variance of c.

In [47]:
np.var(c)

6.666666666666667

#### #4. Print out the shape of the array c

In [48]:
print(c.shape)

(3, 3)


#### #5. Transpose c and print out transposed result.

In [49]:
transposed_results = np.transpose(c)
transposed_results

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [50]:
print(transposed_results.shape)

(3, 3)


#### #6. Get the dot product of the array c with c. 

In [51]:
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

#### #7. Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [52]:
(c * c.transpose()).sum()

261

#### #8. Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [53]:
(c * c.transpose()).prod()

131681894400

<hr style="border:2px solid black">

## Setup #4

In [54]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [55]:
d= np.array(d)

#### #1. Find the sine of all the numbers in d

In [56]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

#### #2. Find the cosine of all the numbers in d

In [57]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

##### #3. Find the tangent of all the numbers in d

In [58]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

#### #4. Find all the negative numbers in d

In [59]:
d[d<0]

array([-90, -30, -45, -45])

#### #5. Find all the positive numbers in d

In [60]:
d[d>0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

#### #6. Return an array of only the unique numbers in d.

In [61]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

#### #7. Determine how many unique numbers there are in d.

In [62]:
np.unique(d).shape[0]

11

#### #8. Print out the shape of d.

In [63]:
print(d.shape)

(3, 6)


#### #9. Transpose and then print out the shape of d.

In [64]:
transpose_d = np.transpose(d)
transpose_d

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

In [65]:
print(transpose_d.shape)

(6, 3)


#### #10. Reshape d into an array of 9 x 2

In [66]:
np.reshape(d, (9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])