# Numpy Exercises

1. How many negative numbers are there?

2. How many positive numbers are there?

3. How many even positive numbers are there?

4. If you were to add 3 to each data point, how many positive numbers would there be?

5. If you squared each number, what would the new mean and standard deviation be?

6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

7. Calculate the z-score for each data point. Recall that the z-score is given by:

Z=(x−μ)/ σ

<hr style="border:2px solid gray">

In [1]:
#import what the exercises call for
import numpy as np

In [2]:
#this is the original numpy array given to us in the exercise
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

#### #1 How many negative numbers are there?
**Answer**: 4

In [3]:
#a negative number is a numer that is less than 0
#so lets take a look at what numbers are < 0
mask_a = a[a<0]
mask_a

array([-2, -1, -6, -7])

In [4]:
#another way to see this would be
#if it is greater than 0 you get False (meaning its a positive number)
#otherwise you get True (meaning its a negative number)
a<0

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [5]:
#one way to capture this without counting... because we want to be lazy
len(a[a<0])

4

In [6]:
#OR we can be more streamlined and use our new mask..
len(mask_a)

4

In [7]:
#another way to capture this is by using .shape
a[a<0].shape[0]

4

<hr style="border:0.5px solid black">

#### #2 How many positive numbers are there?
**Answer**: 5

In [8]:
#a positive number is a numer that is greatere than 0
#so lets take a look at what numbers are > 0
pos_num = a[a>0]

#let's call that variable
pos_num

array([ 4, 10, 12, 23,  3])

In [9]:
#lets see how MANY psositive numbers are in our array
len(pos_num)

5

In [10]:
#another way to accomplish this
pos_num.shape[0]

5

<hr style="border:0.5px solid black">

#### #3 How many even positive numbers are there?
**Answer**: 3

In [11]:
#first, lets look at our positives again
#pull that from problem 2
pos_num

array([ 4, 10, 12, 23,  3])

In [12]:
#this will give you all the of the even positive #s
#we are creating a variable that takes positive numbers only (a variable we already created),
##divides them by two with 0 remaining (meaning they will be even as well)
pos_and_even = pos_num[pos_num % 2 == 0]

#take a look at the EVEN and POSITIVE numbers within our array
pos_and_even

array([ 4, 10, 12])

In [13]:
#now let's get the length of that for the answer
len(pos_and_even)

3

<hr style="border:0.5px solid black">

#### #4. If you were to add 3 to each data point, how many positive numbers would there be?
**Answer**: 10

In [14]:
#creating a new variable named 'c' that adds 3 to each item in the array
c = a+3

#lets take a look at that original array (a) with 3 added to each number
c

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [15]:
#let's double check by printing a (original array) next to c (our new array)
print(c) #new
print(a) #old

#yes! it did add 3 to each number

[ 7 13 15 26  1  2  3  3  3 -3  6 -4]
[ 4 10 12 23 -2 -1  0  0  0 -6  3 -7]


In [16]:
#now to get the answer of "how many positive numbers there will be"
sum_3 = a[(a + 3) > 0]

len(sum_3)

10

In [17]:
sum_3

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0,  3])

<hr style="border:0.5px solid black">

#### #5. If you squared each number
**Answer**: mean = 74
<br>**Answer**: standard deviation = 144

In [18]:
#First, lets square each number
squared= a**2

#and take a look at the array (squared)
squared

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [19]:
#the mean is the average
#name a variable that uses our new variable of 'squared' and uses .mean to find the mean of our new squared array
mean = squared.mean()

#let's call the variable to get our answer
mean

74.0

In [20]:
#name a variable standdev that uses our new variable of 'squared' and uses .std for standard deviation
standev = squared.std()

#let's call the new variable to get our answer
standev

144.0243035046516

In [21]:
#Let's put it all together
squared = a ** 2
print('The new mean is {}.'.format(squared.mean()))
print('The new standard deviation is {}.'.format(squared.std()))

The new mean is 74.0.
The new standard deviation is 144.0243035046516.


In [22]:
#OR we can use the new variable we created above
#Let's put it all together

print(f"The new mean is {mean}")
print(f"The new standard deviation is {standev:.2f}")

The new mean is 74.0
The new standard deviation is 144.02


<hr style="border:0.5px solid black">

#### #6: A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.
<br> **Answer**: array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0., -10.]) 

<div class="alert-info">
    <b>Why do we 'center' our data sets??</b>
<br>    
Take a look at these link: <br>
    - https://www.statsimprove.com/en/centering-the-variables-what-it-means-and-what-it-is-used-for-2/
    <br>
    - https://www.theanalysisfactor.com/centering-and-standardizing-predictors/
<br>    

Centering will become more clear when we get into modeling.
</div>

In [23]:
#let's see what 'a' looks like
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [24]:
#now let's find the mean of our array
#we get 3
a.mean()

3.0

In [25]:
#So, if we are going to "center the data set", we will subtract the mean (3) from each point
#Center the original dataset by subtracting the mean from each data point

#Let's create a variable that holds that act
centered_a = a - a.mean()

In [26]:
#double check by looking at the MEAN of our new 'centered' array 
#it should be 0
centered_a.mean()

0.0

In [27]:
#Take a look at what that new 'centered' array looks like
centered_a

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

<hr style="border:0.5px solid black">

#### #7 Calculate the z-score for each data point. Recall that the z-score is given by:
Z=(x−μ)/ σ

<div class="alert-info">
    <b>What is Z-score??</b>
<br>    
Essentially, Z-score is an indication of how much a given value differs from the standard deviation.
<br>    
For our purposes we will be using z-score in anomaly detection to determine what our outliers are
</div>

In [28]:
z_scores = centered_a / a.std()
z_scores

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

<hr style="border:0.5px solid black">

#### #8 MORE NUMPY PRACTICE
**added to seperate file